### ISSUE TITLE
Once the server is started, the thread cannot finish even after "stop server" command

### ISSUE THREAD

**Issue by edidonet** [annoviko/robotframework-httpctrl#1]
Hey Annoviko,

Thanks for the contribution to the Robot community.
I am using this library and I have noticed an issue when I try to stop the server.
Once the server has been started, Python thread keeps running and it just cannot finish by itself. It needs to have the process killed.
It occurs in both Windows and Linux systems either using the library in Robot or running a Python program.
It there any tip or even a workaround to use in the code for those cases?

Thanks a lot for the attention and for the library development,
Eduardo
[start-stop-server.zip](https://github.com/annoviko/robotframework-httpctrl/files/2971103/start-stop-server.zip)

**Comment by annoviko** [comment]
Hello, @annoviko,

Thank you for your bug report despite the first version hasn't been release yet! I am in process of writing tests and documentation for this library. I will check the problem today and provide correction to it.

**Comment by annoviko** [comment]
@edidonet, I have fixed the problem. In case of start-stop scenario, stop was called before server actual run and as a result it won't be possible to join thread.

And some additional information to your example. Looks like you forget to call 'wait_for_request':
```python
from HttpCtrl import Server

server = Server()

server.start_server('localhost', '8808')

server.wait_for_request()   # wait for incoming request
server.reply_by(200)        # reply to it

print ('method -> ' + server.get_request_method())
print ('body -> ' + server.get_request_body())

server.stop_server()
```

**Comment by edidonet** [comment]
@annoviko,  good one!
I was having the same issue in Robot running a wait for request but for some reason Robot cannot handle threads in different test cases, or even running in the setup/teardown steps. I have done a workaround starting and stopping the server in the same test case in order to capture the id I needed.
It's working perfectly! :)

Thanks again for the consideratoin and support,
Eduardo

**Comment by annoviko** [comment]
@edidonet , the library has been significantly updated today: I have corrected several issues, made some improvement, implemented tests for the library and prepared documentation with examples:
https://annoviko.github.io/robotframework-httpctrl/
