### ISSUE TITLE
Http Server fails to start on Windows 10

### ISSUE THREAD

**Issue by giridharkl** [annoviko/robotframework-httpctrl#16]
**Describe the bug**
Wrote a simple test to start the http server
 
**To Reproduce**
Start a server in "Test suite setup"

**Expected behavior**
A http server should start with a given IP address and a PORT

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Python Version: 3.8.1

![image](https://user-images.githubusercontent.com/1477849/104167204-a5036e80-5404-11eb-8747-74ab02254f43.png)

**Comment by annoviko** [comment]
Hello @giridharkl ,

Could you please provide code of the test that you are using?

**Comment by giridharkl** [comment]
Hi,

Thank you for your prompt concern about this bug. Its my mistake, that I added http:// to the IP address. Once I removed it worked fine. Closing the bug, just a false alarm.
Thank you for the good tool. 
Giridhar
