### ISSUE TITLE
Reply By: binary string support

### ISSUE THREAD

**Issue by mpertsov** [annoviko/robotframework-httpctrl#17]
**Is your feature request related to a problem? Please describe.**
It is impossible to reply with the binary string properly (e.g. one containing 0x0a, 0x12 etc. bytes as chars).
Seems like the issue is caused by the conversion inside `http_handler.py`:
```
def __send_response(self, response):
        ...
        if response.get_body() is not None:
            # code from the example below would work if I'll replace the line below with "body = response.get_body()"
            # probably we could either check for the type first and only then apply the encoding function?
            body = response.get_body().encode("utf-8")
            self.send_header('Content-Length', len(body))
```

**Describe the solution you'd like**
I would expect to use it in a following way (which doesn't work right now, of course):
```
${data}=  Evaluate  bytes((0x0a, 0x12, 0x0a))
Reply By  200  ${data}
```

**Describe alternatives you've considered**
No easy ways to overcome this issue are known to me.

**Additional context**
Not a Python/RF expert, may be wrong in my statements.

**Comment by annoviko** [comment]
Hello @mpertsov ,

Thank you for the proposal, I will support it.

**Comment by deckbsd** [comment]
Hello,

That would be great :) I actually need that right now ^^
So like if the content type is application/octet-stream, the body shouldn t be utf8 encoded.

**Comment by annoviko** [comment]
Hello everyone,

Not sure if it still relevant, was able to work on this library for a long time due to personal reasons. Nevertheless, you can pass `bytes` to `Reply By`. There is an example:
```robotframework
    Wait For Request

    ${body bytes}=   Evaluate   bytes((0x0a, 0x12, 0x0a))
    Reply By   200   ${body bytes}
```

There is a test that I was using to check the correctness of the functionality:
```robotframework
Reply by Bytes Body
    [Teardown]  Stop Server
    Initialize Client   127.0.0.1   8000
    Start Server        127.0.0.1   8000

    ${connection}=   Send HTTP Request Async   POST   /post   Post Message

    ${response}=   Get Async Response   ${connection}   1
    Should Be Equal   ${response}   ${None}

    ${body bytes}=   Evaluate   bytes((0x0a, 0x12, 0x0a))
    Wait For Request
    Reply By   200   ${body bytes}

    ${response}=   Get Async Response   ${connection}   1
    ${response body}=   Get Body From Response   ${response}
    ${response body bytes}=   Encode String To Bytes   ${response body}   UTF-8

    Should Be Equal   ${response body bytes}   ${body bytes}
```
