### ISSUE TITLE
Debian 9 installation failed

### ISSUE THREAD

**Issue by giridharkl** [annoviko/robotframework-httpctrl#18]
**Describe the bug**
Tried installing on debian9 using python 3.8. Getting the following errors.

@debian9:/opt/Python-3.8.0$ python3.8 -m pip install robotframework-httpctrl                                                                                                          Collecting robotframework-httpctrl
  Using cached https://files.pythonhosted.org/packages/ca/1a/d3eda7bae778c4fbd06022b17ec61a701c949c3a998a020b73a4bd8eaf2f/robotframework-httpctrl-0.1.6.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xf85hiky/robotframework-httpctrl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xf85hiky/robotframework-httpctrl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-xf85hiky/robotframework-httpctrl/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 35, in <module>
        from setuptools import windows_support
      File "/usr/local/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/usr/local/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.3.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command

**Comment by annoviko** [comment]
Hello @giridharkl ,

Most probably you do not have libffi on your system that is needed for `ctypes` module that is used by the installer. Try to install it and re-install the library:
```
sudo apt-get install libffi-dev
```

**Comment by giridharkl** [comment]
Hi,
Thank you for the input on this issue. Yes after installing libffi-dev, everything was OK.

Thanks
Giridhar
