### ISSUE TITLE
Possibility to clear request storage

### ISSUE THREAD

**Issue by bonsmik** [annoviko/robotframework-httpctrl#2]
I have a application which sends event based data for external system via http. This lib is great for testing data in messages, thanks. I use lib to listen messages with HttpServer

Now the problem is that if e.g. test will fail and there are still incoming unread requests. When starting next test case I receive requests from previous test. 

Here is simplified test cases:
```
Library     HttpCtrl.Server

Test Setup       Initialize HTTP Server
Test Teardown    Terminate HTTP Server

Test One
    
    Do something which will send 2 requests
    
    Wait For Request
    Reply By   200

    # Test case fails here 

    Wait For Request
    Reply By   200

    ${method}=   Get Request Method
    ${url}=      Get Request Url
    ${body}=     Get Request Body

    Should Be Equal   ${method}   POST
  
Test Two
    [Tags]	Tilamuutokset     Apotti
	 
    
    Do something which will send request
    
    Wait For Request
    Reply By   200

    ${method}=   Get Request Method
    ${url}=      Get Request Url
    ${body}=     Get Request Body

    Should Be Equal   ${method}   GET     # fails here because previous case sent 2 post requests

Initialize HTTP Server
    Start Server        127.0.0.1   8101

Terminate HTTP Server
    Stop Server
```

Suggestion: 
"Stop Server" command could read all requests before stopping or then providing a method to clear all requests.

**Comment by annoviko** [comment]
Hello, @bonsmik 
Thank your report, I will introduce required changes to clear queue after Stop Server.

**Comment by annoviko** [comment]
@bonsmik , changes are available on master branch.

**Comment by bonsmik** [comment]
Cheers, seems to be working as expected.
